# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_earcut <- function(polygon) {
    .Call(`_interleave_rcpp_earcut`, polygon)
}

rcpp_interleave <- function(obj) {
    .Call(`_interleave_rcpp_interleave`, obj)
}

rcpp_interleave_point <- function(lst, stride) {
    .Call(`_interleave_rcpp_interleave_point`, lst, stride)
}

rcpp_interleave_line <- function(lst, stride) {
    .Call(`_interleave_rcpp_interleave_line`, lst, stride)
}

rcpp_interleave_triangle <- function(obj, properties) {
    .Call(`_interleave_rcpp_interleave_triangle`, obj, properties)
}

.test_list_rows <- function(obj) {
    .Call(`_interleave_test_list_rows`, obj)
}

.test_list_element_count <- function(obj) {
    .Call(`_interleave_test_list_element_count`, obj)
}

.test_unlist_list <- function(obj) {
    .Call(`_interleave_test_unlist_list`, obj)
}

