# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_earcut <- function(polygon) {
    .Call(`_interleave_rcpp_earcut`, polygon)
}

rcpp_interleave <- function(obj) {
    .Call(`_interleave_rcpp_interleave`, obj)
}

rcpp_interleave_point <- function(obj, stride) {
    .Call(`_interleave_rcpp_interleave_point`, obj, stride)
}

rcpp_interleave_line <- function(obj, stride) {
    .Call(`_interleave_rcpp_interleave_line`, obj, stride)
}

rcpp_interleave_triangle <- function(obj) {
    .Call(`_interleave_rcpp_interleave_triangle`, obj)
}

